//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Options
    {
        public int id { get; set; }
        public string Text { get; set; }
        public int QuestionID { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
